name: flutter_sweep
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.5

executables:
  fluttersweep: bin/flutter_sweep.dart

dependencies:
  collection: ^1.18.0
  path: ^1.9.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0