name: flutter_sweep
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^2.8.1

# Add regular dependencies here.
dependencies:
  collection: ^1.14.13
  path: ^1.8.3

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
