name: fluttersweep
description: Clean all your Flutter projects at once.
version: 1.0.0
repository: https://github.com/MohamadGreatWarrior/fluttersweep

environment:
  sdk: ^3.0.5

executables:
  fluttersweep:

dependencies:
  collection: ^1.18.0
  path: ^1.9.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0